apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80 # A porta externa que você vai acessar (localhost:8080)
      targetPort: 8080 # A porta interna do container
      nodePort: 30001
  type: NodePort # Ou NodePort, para testes locais
