services:
  api:
    image: order
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: spoospoo
      POSTGRES_DB: ordersys
    ports:
      - "4000:5432"

