apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: c3Bvb3Nwb28=

  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: c3Bvb3Nwb28=
