apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-initializer
          image: postgres:latest
          command: ["/bin/sh", "-c"]
          args:
            - psql -h db-service -U postgres -d ordersys -f /etc/config/init.sql
          volumeMounts:
            - name: db-script-volume
              mountPath: /etc/config
      volumes:
        - name: db-script-volume
          configMap:
            name: db-init-scri